--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#282c34"
foreground="#abb2bf"
cursor="#abb2bf"

-- Colors
color0="#282c34"
color1="#e06c75"
color2="#98c379"
color3="#e5c07b"
color4="#61afef"
color5="#c678dd"
color6="#56b6c2"
color7="#abb2bf"
color8="#545862"
color9="#e06c75"
color10="#98c379"
color11="#e5c07b"
color12="#61afef"
color13="#c678dd"
color14="#56b6c2"
color15="#c8ccd4"
