# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#282c34'
foreground='#abb2bf'
cursor='#abb2bf'

# Colors
color0='#282c34'
color1='#e06c75'
color2='#98c379'
color3='#e5c07b'
color4='#61afef'
color5='#c678dd'
color6='#56b6c2'
color7='#abb2bf'
color8='#545862'
color9='#e06c75'
color10='#98c379'
color11='#e5c07b'
color12='#61afef'
color13='#c678dd'
color14='#56b6c2'
color15='#c8ccd4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
