#!/bin/sh

source /home/comfy/.cache/wal/colors.sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#################################################
#              bspc/config                      #
#################################################
#bspc config normal_border_color       "#AA000000"
#bspc config active_border_color       "#AA000000"
#bspc config focused_border_color        "#2f343f"
bspc config border_width                      0
bspc config window_gap                        8
bspc config split_ratio                    0.50
bspc config borderless_monocle             true
bspc config gapless_monocle                true
bspc config borderless_tiling              true
bspc config focus_follows_pointer          true
bspc config border_radius                     8

###################################
#           bspc/Rules            #
###################################
bspc rule -a Emacs    desktop=^5 state=floating
bspc rule -a Feh      desktop=^4
bspc rule -a Chromium desktop=^2
bspc rule -a Oblogout desktop=^2 state=floating
bspc rule -a WhatsApp desktop=^7

##############################
#         autostart          #
##############################
sxhkd &
compton &
urxvtd &
urxvtc &
conky &
nitrogen --restore &
bash ~/bin/bars/polybar/start_polybar
redshift >/dev/null 2>&1 &
numlockx on &

##################################################
#                Double Monitors                 #
##################################################
xrandr | grep "HDMI1 connected" || export ONE_MONITOR="YES"

if [ "$ONE_MONITOR" == "YES" ]; then
	echo ''
else
	bash /home/comfy/bin/screen/xrandr-hdmi
fi
