#!/bin/sh

source /home/comfy/.cache/wal/colors.sh

sxhkd &

bspc monitor -d I II III IV V VI

#################################################
#              bspc/config                      #
#################################################
bspc config normal_border_color        "$color1"
bspc config active_border_color        "$color7"
bspc config focused_border_color       "$color5"
bspc config border_width                      0
bspc config window_gap                        8
bspc config split_ratio                    0.50
bspc config borderless_monocle             true
bspc config gapless_monocle                true
bspc config borderless_tiling              true
bspc config focus_follows_pointer          true
bspc config border_radius                     6

###################################
#           bspc/Rules            #
###################################
bspc rule -a Emacs    desktop=^5 state=floating
bspc rule -a Feh      desktop=^4
bspc rule -a Chromium desktop=^2
bspc rule -a Oblogout            state=floating
bspc rule -a WhatsApp desktop=^6

##############################
#         autostart          #
##############################
sxhkd &
/home/comfy/bin/x11/compton &
urxvtd &
urxvtc &
conky &
nitrogen --restore &
bash ~/bin/bars/polybar/start_polybar
redshift >/dev/null 2>&1 &
numlockx on &

##################################################
#                Double Monitors                 #
##################################################
xrandr | grep "HDMI1 connected" || export ONE_MONITOR="YES"

if [ "$ONE_MONITOR" == "YES" ]; then
	echo ''
else
	bash /home/comfy/bin/screen/xrandr-hdmi
fi

##################################################
#               Dunst + Pywal                    #
##################################################

killall dunst
dunst -lb "$background" -nb "$background" -cf "$foreground" -lf "$background" -nf "$background" -cf "$foreground" &
